name: Build windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'     
        required: true
        default: 'master'

jobs:
  build_windows:
    
    runs-on: windows-latest

    steps:
         
    # Creation of the ..\downloads directory
    - name: Creation of the "..\downloads" directory
      run: mkdir ..\downloads
      shell: cmd
      working-directory: .\
    
    # Creation of the ..\tools directory
    - name: Creation of the "..\tools" directory
      run: mkdir ..\tools
      shell: cmd
      working-directory: .\
         
    # Installation of jom
    - name: Installation of the jom
      run: |
           Invoke-WebRequest http://download.qt.io/official_releases/jom/jom.zip -OutFile ..\downloads\jom.zip
           Expand-Archive '..\downloads\jom.zip' '..\tools\jom' 
      shell: powershell
      
    # Add jom to path
    - name: Add jom to path
      #run: echo "::add-path::D:/a/${{ github.event.repository.name }}/tools/jom/"
      run: echo "D:/a/${{ github.event.repository.name }}/tools/jom/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    # Installation of Python
    - name: Installation of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Checkout the target project's revision
    - name: Checkout of the project
      uses: actions/checkout@v2
      with:
        repository: svlad-90/${{ github.event.repository.name }}
        path: .\
        ref: ${{ github.ref }}

    # Create build directory
    - name: Creation of the ".\build" directory
      run: mkdir ..\build
      shell: cmd
      working-directory: .\

    #CMake execution
    - name: CMake
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsx86_amd64.bat"
        cmake ..\${{ github.event.repository.name }}\DMA_Plantuml "-GCodeBlocks - NMake Makefiles JOM" "-DCMAKE_BUILD_TYPE:STRING=Release"
      shell: cmd
      working-directory: ..\build
    
    # Build of the project
    - name: Jom
      run: |
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsx86_amd64.bat"
        jom.exe -j8
      shell: cmd
      working-directory: ..\build
      
    # Unit-tests execution
    - name: unit-tests
      run: | 
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsx86_amd64.bat"
        ctest.exe --force-new-ctest-process .\
      shell: cmd
      working-directory: ../build
